nelmio_api_doc:
    documentation:
        info:
            title: API Template
            description: API Template en Symfony 4. Autenticación de usuarios por JWT y manejo de roles y acciones.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under / except /doc
